---
title: "preprocessing"
output: html_document
date: "2024-05-30"
---

## R scripts for preprocessing of the data for section 4 (rawd1.csv)

```{r}
#Use the following package for preprocesssing 

install.packages("tidyverse")
library(tidyverse)
```

Edit the raw data

```{r}
#Read the raw data from the data folder of the repository:
rawd1 <- read.csv('../data/rawd1.csv')
rawd1 <- as.tibble(rawd1)

#Give colnames to the rawd1 file
colnames(rawd1) <- c("subject", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48")

#Pivot alternation to create a csv in long format
d1 <- rawd1 |> pivot_longer(cols=c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48"), names_to="item", values_to="Rating")

#Define the Anim values and Trans values of the 48 items (example sentences) for each participant. 

anim <- c(rep(c(rep("basic", 3), rep("inverse", 3)), 8))
trans <- c(rep(c(9, 8, 7, 6, 5, 4, 3, 2), each=6))

#Copying the above set of values by 205 to fill in the entire Anim and Trans columns of all participants (n=205).

d1 <- mutate(d1, Anim=rep(anim, 205))
d1 <- mutate(d1, Trans=rep(trans, 205))



#Check the resulting data
print(d1)
```

The resulting data, d1.csv, is already stored in the "data" folder.

## R scripts for preprocessing of the data for section 5 (rawd1.csv)

Edit the raw data

```{r}
#Read the raw data from the data folder of the repository:
rawd2 <- read.csv('../data/rawd2.csv')
rawd2 <- as.tibble(rawd2)

#Give colnames to the rawd1 file

#Pivot alternation to create a csv in long format
colnames(rawd2) <- c("subject", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40")

d2 <- rawd2 |> pivot_longer(cols=c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40"), names_to="item", values_to="Rating")

#Define the Anim values and Trans values of the 48 items (example sentences) for each participant. 

caus <- c(rep("Phys", 8), rep("Inst", 8), rep("Aff", 8), rep("Loc", 8), rep("Poss", 8))
transcf <- c(9, 6, 9, 6, 5, 7, 9, 5,7, 5, 7, 5,8, 4, 3, 5,4, 5, 5, 5,4, 5, 5, 5, 4, 3, 4,3, 3, 3,2, 3, 2, 2, 2,1, 2, 2, 2, 1)

#Copying the above set of values by 205 to fill in the entire Anim and Trans columns of all participants (n=205).

d2 <- mutate(d2, Caus=rep(caus, 198))
d2 <- mutate(d2, Trans=rep(transcf, 198))

#Set each row to their appropriate types of variable (character, factor, ordered factor, etc.)
d2$subject <- as.character(d2$subject)
d2$item <- as.character(d2$item)
d2$Rating <- as.ordered(d2$Rating)
d2$Caus <- as.factor(d2$Caus)
d2$Trans <- as.ordered(d2$Trans)

```

The resulting data, d2.csv, is already stored in the "data" folder.
